version: "3.9"
services:
  db:
    image: mysql:8
    container_name: myapp_db
    ports:
      - "53306:3306"
    environment:
      MYSQL_DATABASE: "myapp_db"
      MYSQL_ROOT_PASSWORD: "rootpass"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
