# import os
# import django
# os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings')
# django.setup()

# from myapp.models import Book, Publisher, Author
from django.db.models import Count, Max


# ret1 = Book.objects.filter(title__contains="")
# print(ret1)
# ret2 = Book.objects.filter(publish_date__year=2018)
# print(ret2)
# ret3 = Book.objects.filter(publish_date__year=2017).values("title")
# print(ret3)
# # __gt : ~보다 크다, __gte : ~보다 크거나 같다, __lt : ~보다 작다, __lte : ~보다 작거나 같다
# ret4 = Book.objects.filter(price__gt=10)
# print(ret4)
# ret5 = Book.objects.filter(price__gt=10).values("title", "price")
# print(ret5)
# ret6 = Book.objects.filter(memo__isnull=True)
# print(ret6)
# ret7 = Publisher.objects.filter(name__startswith="Shahe")
# ret8 = Publisher.objects.all()
# print(ret7)
# print(ret8)
# ret9 = Book.objects.filter(publisher__name="出版社")
# print(ret9)
# qs = Publisher.objects.all().annotate(max=Max("book__price")).values("name","max")
# breakpoint()
# ret10 = Publisher.objects.all().annotate(max=Max("book__price")).values("name","max")
# ret10 = Publisher.objects.annotate(max=Max("book__price")). values()
# for i in ret10:
#         print(i)
# annotate: '필드'를 추가, 그룹핑, Count 사용할때 사용
# qs = Publisher.objects.annotate(count=Count("book__title")).values("name", "count")
# breakpoint()
# ret11 = Publisher.objects.annotate(count=Count("book__title")).values("name", "count")
# print(ret11)
# ret12 = Author.objects.filter(name__contains="small")
# print(ret12)
# ret13 =  Author.objects.filter(age__gt=30)
# print(ret13)
# ret14 = Author.objects.filter(phone__startswith=155)
# print(ret14)
# ret15 = Author.objects.filter(phone__startswith=155).values("name", "age")
# print(ret15)
# ret16 = Book.objects.values("author").annotate(max=Max("price")).values("author", "max")
# for i in ret16:
#         print(i)
# qs = Author.objects.all().annotate(count=Count("books__title")).values("name", "count")
# # ret17 = Author.objects.all().annotate(count=Count("books__title")).values("name", "count")
# breakpoint()
# print(ret17)
# qs = Publisher.objects.filter(book__title="o")
# breakpoint()
# ret18 = Publisher.objects.filter(book__title="o")
# print(ret18)
# ret19 = Publisher.objects.filter(book__title="Learn to open a").values("city")
# print(ret19)
# ret20 = Publisher.objects.get(book__title="Learn to open a")
# print(ret20)
# qs = Publisher.objects.get(book__title="Learn to open a").book_set.all().exclude(title="Learn to open a").values("title","price")
# breakpoint()
# pub_obj = Publisher.objects.get(book__title="Learn to open a")
# ret21 = pub_obj.book_set.all().exclude(title="Learn to open a").values("title","price")
# print(ret21)
# print(str(ret21.query))
# ret25 = Author.objects.filter(books__title="Learn to open a")
# for i in ret25:
#     print(i.books.all().values("title", "price"))
# ret = Book.objects.aggregate(Max("price"))
# print(ret)

# print(Book.objects.get(id__exact=3))
